--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/lokiPM/RulesPM
build-by-default: false
branches:
- main
projects:
  RulesPM:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
