name: RulesPM
version: 1.0.1
api: 5.0.0
main: lokiPM\RulesPM\Main
src-namespace-prefix: lokiPM\RulesPM

commands:
 rules:
  description: Show Rules UI.
  permission: rulesPM.use
  default: true

permissions: 
 rulesPM.use:
  default: true
